name: RankManager
main: ifteam\RankManager\RankManager
author: ifteam
version: 1.3-Alpha
api: 
- 3.0.0-ALPHA7

permissions:
 rankmanager.rankshop.create:
  default: OP
 rankmanager.rankshop.delete:
  default: OP
 rankmanager.rankshop.use:
  default: true
 rankmanager.rank.manage:
  default: true
 rankmanager.rank.control:
  default: OP